/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

    @Test
    void testRolls() {
        Library sut = new Library();
        sut.roll(6);
        sut.roll(5);
        assertEquals(5, sut.roll(5).size(), "The following, testRolls, did not pass");
    }

    @Test
    void testContainsDuplicates() {
        Library sut = new Library();
        int[] array = {1,2,4,5,6,6};
        int[] array2 = {1,2,4,5,6};
        assertTrue(sut.containsDuplicates(array), "The following, testContainsDuplicates, did not pass.");
    }

    @Test
    void testFindAverage() {
        Library sut = new Library();
        int[] array = {1,2,4,5,6,6};
        assertEquals(4, sut.averageOfArray(array), "The following, testFindAverage did not pass.");
    }

    @Test
    void testArraysOfArrays() {
        Library sut = new Library();

        int[][] arrayOfArray = {
                {12, 64, 58},
                {133, 12, 13},
                {3, 10, 123},
                {5, 5, 5}};

        sut.highestAverageArray(arrayOfArray);
        assertEquals("[5, 5, 5]", sut.highestAverageArray(arrayOfArray), "The following, testArraysOfArrays did not pass.");
    }
}

