/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

    @Test
    void testRolls() {
        Library sut = new Library();
        sut.roll(6);
        sut.roll(5);
        assertEquals(5, sut.roll(5).size(), "The following, testRolls, did not pass");
    }

    @Test
    void testContainsDuplicates() {
        Library sut = new Library();
        int[] array = {1,2,4,5,6,6};
        int[] array2 = {1,2,4,5,6};
        assertTrue(sut.containsDuplicates(array), "The following, testContainsDuplicates, did not pass.");
    }

    @Test
    void testFindAverage() {
        Library sut = new Library();
        int[] array = {1,2,4,5,6,6};
        assertEquals(4, sut.averageOfArray(array), "The following, testFindAverage did not pass.");
    }

    @Test
    void testArraysOfArrays() {
        Library sut = new Library();

        int[][] arrayOfArray = {
                {12, 64, 58},
                {133, 12, 13},
                {3, 10, 123},
                {5, 5, 5}};

        sut.highestAverageArray(arrayOfArray);
        assertEquals("[5, 5, 5]", sut.highestAverageArray(arrayOfArray), "The following, testArraysOfArrays did not pass.");
    }


    @Test
    void testAnalyzeWeatherData() {
        Library sut = new Library();

        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };

        assertEquals("Min: 51\n" +
                "Max: 72\n" +
                "Never saw temperature: 63\n" +
                "Never saw temperature: 67\n" +
                "Never saw temperature: 68\n" +
                "Never saw temperature: 69",
                sut.analyzeWeatherData(weeklyMonthTemperatures),
                "The following function, analyzeWeatherData, did not pass."
        );

    };

    @Test
    void testTallyVotes() {
        Library sut = new Library();

        String[] votes = {"Bush","Bush","Bush","Bush","Hedge","Hedge" };
        String[] votes2 = {"Cat", "Frog", "Dog", "Dog"};

        assertEquals("Bush received the most votes!", sut.tally(votes), "The following function, tally, did not pass.");
        assertEquals("Dog received the most votes!", sut.tally(votes2), "The following function, tally, did not pass.");

    }

}

