/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package practice;

import practice.Monsters.Demon;
import practice.Monsters.Monster;

public class App {

    public static void main (String[] args) {

        Monster demon = new Demon("Overlord Mal'ganus", "humanoid", true, 100, "red");
        Monster giant = new Monster("Frost Giant Galmo", "big humanoid", true, 40, "white");
        System.out.println(demon);
        System.out.println(demon.speak());
        System.out.println(demon.getWeapon());
        System.out.println(giant);
        System.out.println(giant.speak());
        System.out.println(giant.getWeapon());
    }
}
