/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package practice;

import org.junit.jupiter.api.Test;
import practice.Monsters.Monster;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App sut = new App();

        Monster deer = new Monster("Fawn", "mammal", true, 3, "brown");
        System.out.println(deer);
    }
}
